# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33bf752560ccc53f11b7ba0f72dd9ea8b1f07a32ac49390fb52f0abb7911be068d77f46d0d0651ec41985df29697c89735439bb279ea056bc5fe280574281251

test:
  secret_key_base: e568b43c7cc9fe2aaa0e23354224c78f59d45941d114a42f4e08580e98418e5087b327a3fa3167c29eab676eef9c9bc44b90f645b0ef61348f5ae9a20b4c4435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
